extends Control
## DEV DEMO (not the real game UI): renders a generated roster so we can see the M1
## data layer running in the actual engine. Dual-mode — prints JSON then quits when
## headless, otherwise builds an on-screen table. Throwaway scaffolding for the M9 dashboard.

const ROSTER_RECIPE := [
	"Floor General", "Slasher", "3-and-D Wing", "Two-Way Star",
	"Rim Protector", "Sharpshooter", "Glue Guy", "Stretch Big",
	"Bruiser", "Project", "Slasher", "Floor General",
]
const SEED := 20260614

func _ready() -> void:
	var roster := _build_roster()
	_print_json(roster)
	if DisplayServer.get_name() == "headless":
		get_tree().quit()
		return
	_build_ui(roster)

func _build_roster() -> Array[PlayerData]:
	var rng := RandomNumberGenerator.new()
	rng.seed = SEED
	var out: Array[PlayerData] = []
	var i := 0
	for arch in ROSTER_RECIPE:
		out.append(PlayerGenerator.generate_player(rng, {"archetype": arch, "id": 1000 + i}))
		i += 1
	out.sort_custom(func(a, b): return a.overall() > b.overall())
	return out

func _team_ovr(roster: Array, n: int) -> float:
	var c := mini(n, roster.size())
	var s := 0.0
	for k in c:
		s += float(roster[k].overall())
	return s / float(c)

func _print_json(roster: Array) -> void:
	var arr := []
	for p in roster:
		arr.append({
			"name": p.full_name(), "pos": p.primary_pos, "age": p.age, "height_cm": p.height_cm,
			"archetype": p.archetype, "ovr": p.overall(), "pot": p.potential, "attrs": p.attributes,
		})
	print("ROSTER_JSON_BEGIN")
	print(JSON.stringify({"starters_ovr": _team_ovr(roster, 5), "players": arr}))
	print("ROSTER_JSON_END")

func _build_ui(roster: Array) -> void:
	var bg := ColorRect.new()
	bg.color = Color("0e1116")
	bg.set_anchors_preset(Control.PRESET_FULL_RECT)
	add_child(bg)

	var margin := MarginContainer.new()
	margin.set_anchors_preset(Control.PRESET_FULL_RECT)
	for side in ["left", "top", "right", "bottom"]:
		margin.add_theme_constant_override("margin_" + side, 48)
	add_child(margin)

	var vb := VBoxContainer.new()
	vb.add_theme_constant_override("separation", 14)
	margin.add_child(vb)

	var title := Label.new()
	title.text = "HOOPS CITY  —  Roster Preview"
	title.add_theme_font_size_override("font_size", 40)
	vb.add_child(title)

	var sub := Label.new()
	sub.text = "Generated by the M1 player engine  ·  Starters OVR %.1f  ·  seed %d" % [_team_ovr(roster, 5), SEED]
	sub.add_theme_color_override("font_color", Color("8aa0b4"))
	vb.add_child(sub)

	var grid := GridContainer.new()
	grid.columns = 8
	grid.add_theme_constant_override("h_separation", 26)
	grid.add_theme_constant_override("v_separation", 8)
	vb.add_child(grid)

	for h in ["", "NAME", "POS", "AGE", "HT", "ARCHETYPE", "OVR", "POT"]:
		grid.add_child(_cell(h, Color("6f8194"), 16))

	var idx := 1
	for p in roster:
		var tag := ("%d  ★" % idx) if idx <= 5 else ("%d" % idx)
		grid.add_child(_cell(tag, Color("4a5a6a"), 20))
		grid.add_child(_cell(p.full_name(), Color("e6edf3"), 20))
		grid.add_child(_cell(p.primary_pos, Color("c9d4de"), 20))
		grid.add_child(_cell(str(p.age), Color("c9d4de"), 20))
		grid.add_child(_cell("%d" % p.height_cm, Color("c9d4de"), 20))
		grid.add_child(_cell(p.archetype, Color("9fb3c6"), 20))
		grid.add_child(_cell("%d" % p.overall(), _ovr_color(p.overall()), 20))
		grid.add_child(_cell("%d" % p.potential, Color("7d8fa0"), 20))
		idx += 1

func _cell(txt: String, col: Color, fsize: int) -> Label:
	var l := Label.new()
	l.text = txt
	l.add_theme_color_override("font_color", col)
	l.add_theme_font_size_override("font_size", fsize)
	return l

func _ovr_color(ovr: int) -> Color:
	if ovr >= 70:
		return Color("57d977")
	if ovr >= 60:
		return Color("b6e36a")
	if ovr >= 50:
		return Color("e6d36a")
	return Color("d98c6a")
